WAIT_BETWEEN_ACCOUNTS = (10, 20)  # in seconds

MAX_TRIES = 2

RPC = 'https://opbnb-mainnet-rpc.bnbchain.org'

THREADS_NUM = 1

MOBILE_PROXY = False
DISABLE_SSL = False

UPDATE_STORAGE_ACCOUNT_INFO = False

SKIP_FIRST_ACCOUNTS = 0
RANDOM_ORDER = False

AUTO_UPDATE_INVITES = True
AUTO_UPDATE_INVITES_FROM_FIRST_COUNT = (2, 10)

FAKE_TWITTER = True

DO_TASKS = True
CLAIM_DAILY_INSIGHT = True
CLAIM_RANK_INSIGHTS = True

MIN_INSIGHTS_TO_OPEN = 5

CHECKER_UPDATE_STORAGE = False
