WAIT_BETWEEN_ACCOUNTS = (10, 20)  # in seconds

MAX_TRIES = 3

RPC = 'https://opbnb-mainnet-rpc.bnbchain.org'

THREADS_NUM = 1

MOBILE_PROXY = False
DISABLE_SSL = False

SKIP_FIRST_ACCOUNTS = 0

AUTO_UPDATE_INVITES = False
AUTO_UPDATE_INVITES_FROM_FIRST_COUNT = 1

FAKE_TWITTER = False

DO_TASKS = True
CLAIM_DAILY_INSIGHT = False
CLAIM_RANK_INSIGHTS = False

MIN_INSIGHTS_TO_OPEN = 5
